#include <Arduino.h>
#include <ArduinoJson.h>
#include <TFT_eSPI.h>
#include <WiFi.h>
#include <Preferences.h>
#include <NimBLEDevice.h>
#include <cstring>

 TFT_eSPI tft; Preferences prefs; JsonDocument metrics; unsigned long lastFrame=0,lastSwitch=0; int screen=0; bool demo=false; const int SCREEN_COUNT=9; const char* names[]={"RESUMO","CPU","GPU","RAM","INTERNET","JOGO","DISCORD","SISTEMA","TEMPERATURAS"};
String wifiSsid,wifiPass; const char* SERVICE="8c9f0001-3c3b-4b2b-a001-espmonitor"; const char* RX="8c9f0002-3c3b-4b2b-a001-espmonitor";

void drawHeader(){tft.fillScreen(TFT_BLACK);tft.setTextColor(TFT_CYAN,TFT_BLACK);tft.setTextSize(1);tft.drawString("PC MONITOR / ESP32-S3",8,6);tft.drawFastHLine(8,18,224,TFT_DARKGREY);tft.setTextColor(TFT_WHITE,TFT_BLACK);tft.setTextSize(2);tft.drawString(names[screen],8,28);}
String number(const char* path,const char* suffix=""){JsonVariant v; if(strcmp(path,"cpu.usage")==0)v=metrics["cpu"]["usage"]; else if(strcmp(path,"cpu.frequency_mhz")==0)v=metrics["cpu"]["frequency_mhz"]; else if(strcmp(path,"gpu.usage")==0)v=metrics["gpu"]["usage"]; else if(strcmp(path,"gpu.temperature")==0)v=metrics["gpu"]["temperature"]["value"]; else if(strcmp(path,"ram.usage")==0)v=metrics["ram"]["usage"]; else if(strcmp(path,"ram.used_gb")==0)v=metrics["ram"]["used_gb"]; else if(strcmp(path,"ram.total_gb")==0)v=metrics["ram"]["total_gb"]; else if(strcmp(path,"network.download_mbps")==0)v=metrics["network"]["download_mbps"]; else if(strcmp(path,"network.upload_mbps")==0)v=metrics["network"]["upload_mbps"]; else if(strcmp(path,"cpu.temperature.value")==0)v=metrics["cpu"]["temperature"]["value"]; if(v.isNull()) return "indisponivel"; return String(v.as<float>(),1)+suffix;}
void draw(){drawHeader();tft.setTextSize(2); if(demo){tft.setTextColor(TFT_ORANGE);tft.drawString("DEMO",176,30);} else if(WiFi.status()!=WL_CONNECTED){tft.setTextColor(TFT_RED);tft.drawString("OFFLINE",155,30);} else {tft.setTextColor(TFT_GREEN);tft.drawString("LIVE",184,30);}tft.setTextColor(TFT_WHITE); if(screen==0){tft.drawString("CPU "+number("cpu.usage","%"),8,65);tft.drawString("GPU "+number("gpu.usage","%"),8,90);tft.drawString("RAM "+number("ram.usage","%"),8,115);tft.drawString("NET "+number("network.download_mbps","M"),8,140);tft.drawString(metrics["game"]["name"]|"Nenhum jogo",8,170);}else if(screen==1){tft.drawString(metrics["host"]["cpu"]|"CPU indisponivel",8,68);tft.drawString("Uso "+number("cpu.usage","%"),8,100);tft.drawString("Freq "+number("cpu.frequency_mhz","MHz"),8,130);tft.drawString("Nucleos "+String((int)(metrics["cpu"]["cores"]|0)),8,160);}else if(screen==2){tft.drawString(metrics["gpu"]["name"]|"GPU indisponivel",8,68);tft.drawString("Uso "+number("gpu.usage","%"),8,100);tft.drawString("Temp "+number("gpu.temperature","C"),8,130);}else if(screen==3){tft.drawString("Usada "+number("ram.used_gb","GB"),8,72);tft.drawString("Total "+number("ram.total_gb","GB"),8,105);tft.drawString("Uso "+number("ram.usage","%"),8,138);}else if(screen==4){tft.drawString("Down "+number("network.download_mbps","Mb/s"),8,75);tft.drawString("Up "+number("network.upload_mbps","Mb/s"),8,108);tft.drawString(metrics["network"]["status"]|"indisponivel",8,141);}else if(screen==5){tft.drawString(metrics["game"]["name"]|"Nenhum jogo detectado",8,75);tft.drawString("Tempo indisponivel",8,110);}else if(screen==6){tft.drawString(metrics["discord"]["status"]|"indisponivel",8,75);tft.drawString(metrics["discord"]["call"]|"Informacao indisponivel",8,110);}else if(screen==7){tft.drawString(metrics["host"]["name"]|"PC",8,72);tft.drawString(metrics["host"]["os"]|"SO indisponivel",8,104);tft.drawString("Uptime "+String((int)(metrics["host"]["uptime"]|0))+"s",8,136);}else{tft.drawString("Sensores disponiveis",8,72);tft.drawString("CPU "+number("cpu.temperature.value","C"),8,104);tft.drawString("GPU "+number("gpu.temperature.value","C"),8,136);tft.drawString("Sem valores inventados",8,168);}tft.setTextSize(1);tft.setTextColor(TFT_DARKGREY);tft.drawString("BOOT: proxima tela   RESET: reinicia",8,220);}
void onRx(NimBLECharacteristic* c){String s=c->getValue().c_str(); deserializeJson(metrics,s); demo=metrics["demo"]|false;}
class RxCallbacks: public NimBLECharacteristicCallbacks{void onWrite(NimBLECharacteristic* c, NimBLEConnInfo&) override{onRx(c);}};
void setupBle(){NimBLEDevice::init("PC-Monitor-S3");auto* server=NimBLEDevice::createServer();auto* svc=server->createService(SERVICE);auto* rx=svc->createCharacteristic(RX,NIMBLE_PROPERTY::WRITE);rx->setCallbacks(new RxCallbacks());svc->start();NimBLEAdvertising* adv=NimBLEDevice::getAdvertising();adv->addServiceUUID(SERVICE);adv->start();}
void setup(){Serial.begin(115200);tft.init();tft.setRotation(1);prefs.begin("monitor",false);wifiSsid=prefs.getString("ssid","");wifiPass=prefs.getString("pass","");tft.fillScreen(TFT_BLACK);tft.setTextColor(TFT_CYAN);tft.setTextSize(2);tft.drawString("PC MONITOR",35,80);tft.setTextSize(1);tft.drawString("Inicializando comunicacao...",28,110);WiFi.mode(WIFI_STA);if(wifiSsid.length())WiFi.begin(wifiSsid.c_str(),wifiPass.c_str());setupBle();delay(500);}
void loop(){if(Serial.available()){String line=Serial.readStringUntil('\n');deserializeJson(metrics,line);demo=metrics["demo"]|false;}if(WiFi.status()!=WL_CONNECTED && wifiSsid.length() && millis()%10000<50)WiFi.reconnect();if(millis()-lastSwitch>15000){screen=(screen+1)%SCREEN_COUNT;lastSwitch=millis();}if(millis()-lastFrame>250){draw();lastFrame=millis();}delay(5);}
