[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.0.4
  h2zero/NimBLE-Arduino@^2.0.0
  tzapu/WiFiManager@^2.0.17
build_flags = -DUSER_SETUP_LOADED -DILI9341_2_DRIVER -DGC9A01_DRIVER
